config/routes.rb
Rails.application.routes.draw do
  root "basic_search#index"

  get 'analyze', to: 'tacos#analyze'

  get 'libkey', to: 'thirdiron#libkey'
  get 'browzine', to: 'thirdiron#browzine'
  get 'oa_work', to: 'openalex#work'

  get 'record/(:id)',
      to: 'record#view',
      as: 'record',
      :constraints => { :id => /[0-z\.\-\_~\(\)]+/ }
  get 'results', to: 'search#results'
  get 'turnstile', to: 'turnstile#show', as: 'turnstile'
  post 'turnstile/verify', to: 'turnstile#verify', as: 'turnstile_verify'
  get 'style-guide', to: 'static#style_guide'

  get 'boolpref', to: 'static#boolpref'

  get 'robots.txt', to: 'robots#robots'
end

app/controllers/basic_search_controller.rb
class BasicSearchController < ApplicationController
  before_action :set_active_tab

  def index; end
end

app/views/basic_search/_error.html.erb
<% return unless error['message'].present? %>

<div class="alert alert-banner error">
  <%= error['message'] %><br>
  <%= error['extensions']['problems'].pluck("explanation").join %>
</div>

app/views/basic_search/_pagination.html.erb
<% return if @pagination.nil? %>

<div class="gridband layout-3c">
  <div class="grid-item box-content">
    <% if @pagination[:prev] %>
      <%= link_to "Previous page (#{@pagination[:prev]})", "?q=#{params[:q]}&page=#{@pagination[:prev]}" %>
    <% else %>
      First page
    <% end %>
  </div>
  <div class="grid-item box-content">Page <%= @pagination[:page] %> of <%= (@pagination[:hits] / 20) + 1 %></div>
  <div class="grid-item box-content">
    <% if @pagination[:next] %>
      <%= link_to "Next page (#{@pagination[:next]})", "?q=#{params[:q]}&page=#{@pagination[:next]}" %>
    <% else %>
      Last page
    <% end %>
  </div>
</div>

app/views/basic_search/_result.html.erb
<li>
  <h2 class="record-title">
    <span class="sr">Title: </span><%= link_to(result['title'], record_path(result['timdexRecordId'])) %>
  </h2>

  <% result['contentType']&.each do |type| %>
    <p>
      <%= type %>
    <p>
  <% end %>

  <% contributors = [] %>
  <% result['contributors']&.each do |contributor| %>
    <% contributors << "#{contributor['value']} (#{contributor['kind']})" %>
  <% end %>

  <p class="result-authors">
    <span class="sr">Authors: </span>
    <%= contributors.join('; ') %>
  </p>

  <% result['publicationInformation']&.each do |pub| %>
    <p>
      <span class="sr">Publication Information: </span>
      <%= pub %>
    </p>
  <% end %>

  <% result['dates']&.each do |date| %>
    <p>
      <%= date['kind'] %>: <%= date['value'] %>
    </p>
  <% end %>

  <% result['notes']&.each do |note| %>
    <p>
      <%= note['kind'] || 'Note' %>: <%= note['value'].join(' ') %>
    </p>
  <% end %>

  <p>
    Identifier: <%= result['timdexRecordId'] %>
  </p>

  <hr />
</li>

app/views/basic_search/index.html.erb
<%= content_for(:title, index_page_title) %>

<main class="space-wrap">
  <%= render partial: "shared/site_title" %>
  <%= render partial: "search/form_geo" if Feature.enabled?(:geodata) %>
  <%= render partial: "static/about" if ENV.fetch('ABOUT_APP', nil) %>
</main>